server:
  port: 8080

spring:
  kafka:
    topic:
      name: my-topic
    producer:
      bootstrap-servers: kafka_node:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable:
          idempotence: true
        max-in-flight-requests-per-connection: 5
        
    consumer:
      bootstrap-servers: kafka_node:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: my-group
      auto-offset-reset: latest
      isolation-level: read-committed
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: com.dto
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
